# version: "3.9"  ## 最新版では必要ないみたい　https://docs.docker.com/compose/compose-application-model/
services:
  phpmyapp:
    build:
      context: ./phpmyapp #DockerfileをBuildする時のパスの起点が変わる
      dockerfile: ./Dockerfile #Dockerfileのあるパスを指定する
    volumes:
      #パスをマウント <HostPath>:<Container Path>（<HostPath>をコンテナ内では<Container Path>にあるものとして認識する）
      - ./phpmyapp/html:/var/www/html
    ports:
      - ${WEB_PORT}:80 #ポートを公開 <Host IP>:<Host Port>:<Container Port>　${WEB_PORT}は.envファイルで設定
    depends_on:
      - mysql

  mysql:
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
    volumes:
      - ./mysql/mysql:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root #適切に変更
      - MYSQL_DATABASE=test_db #適切に変更
      - MYSQL_USER=test_user #適切に変更
      - MYSQL_PASSWORD=test_password #適切に変更
    ports:
      - ${MYSQL_PORT}:3306

  phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: ./Dockerfile
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "test_user" #適切に変更
      PMA_PASSWORD: "test_password" #適切に変更
    ports:
      - ${PMA_PORT}:80

